### ISSUE TITLE
Version for NPM

### ISSUE THREAD

**Issue by mrded** [thisissoon/angular-addthis#19]
Hello,

Are you planing to publish this on https://www.npmjs.com ?
It will be handy to have npm version.

For now you can install it with following:

    npm i github:thisissoon/angular-addthis#v0.2.2

Thank you.

**Comment by edwardoparearyee** [comment]
@mrded yes we do want to publish to npm, will look at publishing this module sometime soon

**Comment by edwardoparearyee** [comment]
Fixed in #21 

`npm install angular-addthis --save`
