### ISSUE TITLE
Cannot read property 'init'

### ISSUE THREAD

**Issue by tbo47** [thisissoon/angular-addthis#22]
Hi

I have the following error. Any idea why?

angular.js:13642 TypeError: Cannot read property 'init' of undefined
    at Scope.init (http://localhost:9001/vendor/js/angular-addthis/angular-addthis.js:121:36)
    at Object.link (http://localhost:9001/vendor/js/angular-addthis/angular-addthis.js:132:24)
    at http://localhost:9001/vendor/js/angular/angular.js:1266:18

angular 1.5.6
angular-addthis 0.2.4

**Comment by edoparearyee** [comment]
@tla-dev have you added the addthis library to your page?

``` html
<script src="//s7.addthis.com/js/300/addthis_widget.js#pubid={pubid}&async=1"></script>
```

Replace `{pubid}` with your publisher id from your addthis account

**Comment by tbo47** [comment]
no, thank you, i'll do that.
