### ISSUE TITLE
linkedin.com

### ISSUE THREAD

**Issue by tbo47** [thisissoon/angular-addthis#23]
Do you have a linkedin.com button?

**Comment by edoparearyee** [comment]
This library should support any buttons addthis currently offers. I believe the button for LinkedIn would look like: `<a href class="addthis_button_linkedin">LinkedIn</a>`.

You can find the full list of supported services on addthis here: https://www.addthis.com/services. The buttons will look like this: 

``` html
<!-- replace {{ code }} with code for relevant service -->
<a href class="addthis_button_{{ code }}">Share</a>
```
